### ISSUE TITLE
[resource kontena_node] Parallel create fails with a server race condition on node_number allocation

### ISSUE THREAD

**Issue by SpComb** [kontena/terraform-provider-kontena#7]
Known race condition on the server when allocating unique node numbers: https://github.com/kontena/kontena/issues/2071

```
Error applying plan:

1 error(s) occurred:

* module.digitalocean-node1.kontena_node.node: 1 error(s) occurred:

* kontena_node.node: Node create: POST http://207.154.242.14:80/v1/grids/test/nodes => HTTP 500 Internal Server Error: <nil>

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

```
82.181.164.219 - - [28/Jul/2017:13:40:31 +0000] "POST /v1/grids HTTP/1.1" 201 328 0.1722

Mongo::Error::OperationFailure (E11000 duplicate key error index: kontena_server.host_nodes.$grid_id_1_node_number_1 dup key: { : ObjectId('597b3ecf4c7e3b000788a9a7'), : null } (11000)):
  /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/operation/result.rb:256:in `validate!'
  /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/operation/write/insert.rb:55:in `execute_write_command'
  /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/operation/write/write_command_enabled.rb:41:in `execute'
  /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/collection.rb:365:in `block in insert_one'
  /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/retryable.rb:112:in `write_with_retry'
  /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/collection.rb:356:in `insert_one'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/query_cache.rb:182:in `insert_one_with_clear_cache'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable/creatable.rb:79:in `insert_as_root'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable/creatable.rb:27:in `block in insert'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable/creatable.rb:118:in `block (2 levels) in prepare_insert'
  /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
  /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/interceptable.rb:138:in `run_callbacks'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable/creatable.rb:117:in `block in prepare_insert'
  /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
  /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/interceptable.rb:138:in `run_callbacks'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable/creatable.rb:116:in `prepare_insert'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable/creatable.rb:23:in `insert'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable/savable.rb:23:in `save'
  /app/app/mutations/host_nodes/create.rb:42:in `execute'
  /usr/lib/ruby/gems/2.4.0/gems/mutations-0.8.1/lib/mutations/command.rb:80:in `run'
  /usr/lib/ruby/gems/2.4.0/gems/mutations-0.8.1/lib/mutations/command.rb:32:in `run'
  /app/app/routes/v1/grids/grid_nodes.rb:20:in `block (3 levels) in <top (required)>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:767:in `always'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:460:in `is'
  /app/app/routes/v1/grids/grid_nodes.rb:14:in `block (2 levels) in <top (required)>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:767:in `always'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:758:in `_verb'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:540:in `post'
  /app/app/routes/v1/grids/grid_nodes.rb:11:in `block in <top (required)>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda/plugins/multi_route.rb:211:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda/plugins/multi_route.rb:211:in `route'
  /app/app/routes/v1/grids_api.rb:70:in `block (3 levels) in <class:GridsApi>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:832:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/app/routes/v1/grids_api.rb:69:in `block (2 levels) in <class:GridsApi>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:832:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/app/routes/v1/grids_api.rb:55:in `block in <class:GridsApi>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `block in call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `catch'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda/plugins/error_handler.rb:66:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:228:in `block in build_rack_app'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:117:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:660:in `run'
  /app/app/routes/v1_api.rb:13:in `block (2 levels) in <class:Api>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:857:in `match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `block in match_all'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `each'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `all?'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `match_all'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:831:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/app/routes/v1_api.rb:13:in `block in <class:Api>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `block in call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `catch'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:228:in `block in build_rack_app'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:117:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:660:in `run'
  /app/server.rb:54:in `block (2 levels) in <class:Server>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:832:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/server.rb:53:in `block in <class:Server>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `block in call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `catch'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:228:in `block in build_rack_app'
  /app/app/middlewares/version_injector.rb:12:in `call'
  /app/app/middlewares/token_authentication.rb:73:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/static.rb:149:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:147:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
  /app/app/middlewares/websocket_backend.rb:74:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

82.181.164.219 - - [28/Jul/2017:13:40:31 +0000] "POST /v1/grids/test/nodes HTTP/1.1" 500 35 0.1846
```

Works when re-applying.

**Comment by SpComb** [comment]
Should have been fixed server-side in https://github.com/kontena/kontena/pull/2694 for 1.4
